In [ ]:
# Core imports for the whole lab
import numpy as np
import numpy.linalg as la          # inv, norm, eig, solve, matrix_rank
import matplotlib.pyplot as plt

np.set_printoptions(precision=3, suppress=True)   # tidy array printing
np.random.seed(42)
print('Setup complete. NumPy', np.__version__)

Setup complete. NumPy 2.0.2


In [ ]:


scalar = np.array(5)                  # 0-D: a single number
vector = np.array([2, 5, 1])          # 1-D: a list of numbers
matrix = np.array([[1, 2], [3, 4]])   # 2-D: rows x columns
tensor = np.ones((3, 2, 2))           # n-D: a stack of matrices

# .ndim = number of dimensions, .shape = size along each dimension
for name, arr in [('scalar', scalar), ('vector', vector),
                  ('matrix', matrix), ('tensor', tensor)]:
    print(f'{name:7s} ndim={arr.ndim}  shape={arr.shape}')


scalar  ndim=0  shape=()
vector  ndim=1  shape=(3,)
matrix  ndim=2  shape=(2, 2)
tensor  ndim=3  shape=(3, 2, 2)


In [ ]:
A = np.arange(6).reshape(2, 3)   # shape (2, 3)
B = np.ones((2, 3), dtype=int)

print('A:\n', A)
print('A + B (element-wise add):\n', A + B)
print('A.T  (transpose -> shape', A.T.shape, '):\n', A.T)
print('A.reshape(3, 2):\n', A.reshape(3, 2))
print('A.flatten():', A.flatten())

A:
 [[0 1 2]
 [3 4 5]]
A + B (element-wise add):
 [[1 2 3]
 [4 5 6]]
A.T  (transpose -> shape (3, 2) ):
 [[0 3]
 [1 4]
 [2 5]]
A.reshape(3, 2):
 [[0 1]
 [2 3]
 [4 5]]
A.flatten(): [0 1 2 3 4 5]


In [ ]:


T = np.arange(12).reshape(3, 4)
print('T:\n', T)

# 1. ndim and shape
import numpy as np

T = np.arange(12).reshape(3, 4)
print("T:\n", T)

print("Number of Dimensions:", T.ndim)
print("Shape:", T.shape)

# 2. T + T
import numpy as np

T = np.arange(12).reshape(3, 4)

print(T + T)

# 3. Transpose (print .T.shape) and reshape to (2, 6)
import numpy as np

T = np.arange(12).reshape(3, 4)

print(T.T)

print("Shape:", T.T.shape)



T:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
T:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Number of Dimensions: 2
Shape: (3, 4)
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Shape: (4, 3)


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 0, 1])

# Dot product: sum of element-wise products -> measures alignment
print('a . b  (dot)   :', np.dot(a, b))      # 1*4 + 2*0 + 3*1 = 7

# Cross product: a new vector perpendicular to both (3-D only)
print('a x b  (cross) :', np.cross(a, b))


a . b  (dot)   : 7
a x b  (cross) : [ 2 11 -8]


In [ ]:
print('L2 norm  ||a||_2 :', la.norm(a))         # sqrt(sum of squares)
print('L1 norm  ||a||_1 :', la.norm(a, 1))      # sum of absolute values
print('Linf norm        :', la.norm(a, np.inf)) # max absolute value

# Cosine similarity: the angle between vectors, ignoring magnitude
def cosine(u, v):
    return np.dot(u, v) / (la.norm(u) * la.norm(v))

print('cosine(a, b)     :', round(cosine(a, b), 3))


L2 norm  ||a||_2 : 3.7416573867739413
L1 norm  ||a||_1 : 6.0
Linf norm        : 3.0
cosine(a, b)     : 0.454


In [ ]:
import numpy as np
import numpy.linalg as la

A = np.array([[2., 0.],
              [0., 3.]])

vals, vecs = la.eig(A)

print("Eigenvalues (lambda):", vals)
print("Eigenvectors (columns):\n", vecs)

Eigenvalues (lambda): [2. 3.]
Eigenvectors (columns):
 [[1. 0.]
 [0. 1.]]


In [ ]:
for i in range(len(vals)):
    v = vecs[:, i]                 # i-th eigenvector
    lhs = A @ v                    # A v
    rhs = vals[i] * v              # lambda v
    print(f'lambda={vals[i]:.1f}  A v == lambda v ?', np.allclose(lhs, rhs))

lambda=2.0  A v == lambda v ? True
lambda=3.0  A v == lambda v ? True


In [ ]:
C = np.array([[4., 1.],
              [2., 3.]])

# 1. eigenvalues and eigenvectors
import numpy as np
import numpy.linalg as la

C = np.array([[4., 1.],
              [2., 3.]])

# Eigenvalues and Eigenvectors
values, vectors = la.eig(C)

print("Eigenvalues:")
print(values)

print("\nEigenvectors:")
print(vectors)
# 2. print eigenvalues
print("Eigenvalues are:")
print(values)

# 3. verify A v = lambda v for the first eigenvector
# First eigenvalue
lambda1 = values[0]

# First eigenvector
v1 = vectors[:, 0]

# Left-hand side
lhs = C @ v1

# Right-hand side
rhs = lambda1 * v1

print("C @ v1 =")
print(lhs)

print("\nlambda * v1 =")
print(rhs)

print("\nVerification:", np.allclose(lhs, rhs))

Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.707 -0.447]
 [ 0.707  0.894]]
Eigenvalues are:
[5. 2.]
C @ v1 =
[3.536 3.536]

lambda * v1 =
[3.536 3.536]

Verification: True


In [ ]:
A = np.array([[ 2.,  1., -1.],
              [-3., -1.,  2.],
              [-2.,  1.,  2.]])
b = np.array([8., -11., -3.])

x = la.solve(A, b)
print('Solution x:', x)                    # [2, 3, -1]
print('Rank of A :', la.matrix_rank(A))     # 3 -> full rank
print('Full rank -> a unique solution exists')

Solution x: [ 2.  3. -1.]
Rank of A : 3
Full rank -> a unique solution exists


In [ ]:
# A rank-deficient matrix: row 3 = row 1 + row 2 (not independent)
D = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [5., 7., 9.]])
print('Rank of D:', la.matrix_rank(D), '-> < 3, so rows are dependent')

Rank of D: 2 -> < 3, so rows are dependent


In [ ]:

# Toy 4-D embeddings (in practice these come from a model)
king  = np.array([0.8, 0.6, 0.1, 0.2])
queen = np.array([0.7, 0.7, 0.1, 0.3])
apple = np.array([0.1, 0.0, 0.9, 0.8])

print('cosine(king, queen):', round(cosine(king, queen), 3))   # high
print('cosine(king, apple):', round(cosine(king, apple), 3))   # low



cosine(king, queen): 0.986
cosine(king, apple): 0.267


In [ ]:


A2 = np.array([[3., 2.],
               [1., 4.]])
b2 = np.array([7., 9.])

cat = np.array([0.9, 0.8, 0.1])
dog = np.array([0.85, 0.7, 0.2])
car = np.array([0.1, 0.2, 0.95])

# 1. Solve A2 x = b2
import numpy as np
import numpy.linalg as la

A2 = np.array([[3., 2.],
               [1., 4.]])
b2 = np.array([7., 9.])

# Solve A2x = b2
x = la.solve(A2, b2)

print("Solution x:")
print(x)


# 2. Rank of A2
rank = la.matrix_rank(A2)

print("Rank of A2:", rank)


# 3. cosine(cat, dog) and cosine(cat, car); which is more similar?
cat = np.array([0.9, 0.8, 0.1])
dog = np.array([0.85, 0.7, 0.2])
car = np.array([0.1, 0.2, 0.95])

# Cosine(cat, dog)
cos_cat_dog = np.dot(cat, dog) / (la.norm(cat) * la.norm(dog))

# Cosine(cat, car)
cos_cat_car = np.dot(cat, car) / (la.norm(cat) * la.norm(car))

print("Cosine(cat, dog):", cos_cat_dog)
print("Cosine(cat, car):", cos_cat_car)

if cos_cat_dog > cos_cat_car:
    print("cat is more similar to dog.")
else:
    print("cat is more similar to car.")


Solution x:
[1. 2.]
Rank of A2: 2
Cosine(cat, dog): 0.9946195449838785
Cosine(cat, car): 0.29255678516966266
cat is more similar to dog.
